name: nightly
on:
  push:
    branches: [main, when-i-am-free]
jobs:
  move-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Move ci tag
        run: |
          mkdir repo
          git clone -b "$BRANCH_NAME" "https://github.com/${GITHUB_REPOSITORY}" repo
          cd repo
          bash .github/workflows/move-tag.sh "nightly-build" "Last commit build by the CI"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/when-i-am-free'

  nightly-build:
    needs: [move-tag]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '17'
      - uses: eskatos/gradle-command-action@v1
        with:
          dependencies-cache-enabled: true
          arguments: jlink --info --no-daemon --stacktrace --warning-mode all
      - uses: eskatos/gradle-command-action@v1
        with:
          dependencies-cache-enabled: true
          arguments: fatjar --info --no-daemon --stacktrace --warning-mode all

      - name: Copy lsp-fatjar.jar (Unix)
        run: cp -a ./lsp/build/libs/lsp-*-fat.jar ./lsp-fatjar.jar
        if: matrix.os != 'windows-latest'
      - name: Copy cli-fatjar.jar (Unix)
        run: cp -a ./cli/build/libs/cli-*-fat.jar ./cli-fatjar.jar
        if: matrix.os != 'windows-latest'

      - name: Copy lsp-fatjar.jar (Windows)
        run: copy .\lsp\build\libs\lsp-*-fat.jar .\lsp-fatjar.jar
        if: matrix.os == 'windows-latest'
      - name: Copy cli-fatjar.jar (Windows)
        run: copy .\cli\build\libs\cli-*-fat.jar .\cli-fatjar.jar
        if: matrix.os == 'windows-latest'

      - name: Zip Artifacts (Windows)
        uses: papeloto/action-zip@v1
        with:
          files: ./lsp/build/image
          dest: aya-prover-jlink-${{ matrix.os }}_x86-64.zip
        if: matrix.os == 'windows-latest' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/when-i-am-free')

      - name: Zip Artifacts (Unix)
        run: |
          root="$(pwd)"
          cd ./lsp/build/image
          zip -r "$root/aya-prover-jlink-${{ matrix.os }}_x86-64.zip" .
        if: matrix.os != 'windows-latest'

      - name: Update the CI tag
        uses: Xotl/cool-github-releases@v1
        with:
          mode: update
          isPrerelease: false
          tag_name: nightly-build
          release_name: "Nightly builds"
          body_mrkdwn: |
            _These are latest builds, but the date on GitHub is frozen due to stupid limitations.
            Corresponding commit: <https://github.com/aya-prover/aya-dev/commit/${{ github.sha }}>_
          assets: aya-prover-jlink-${{ matrix.os }}_x86-64.zip;./lsp-fatjar.jar;./cli-fatjar.jar
          replace_assets: true
          github_token: ${{ secrets.GH_TOKEN }}
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/when-i-am-free'

